name: Backend
on:
  pull_request:
    paths:
      - 'backend/**'
  push:
    branches: [ main ]
    paths:
      - 'backend/**'

jobs:
  pre-commit:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: pre-commit/action@v3.0.1
        with:
          extra_args: --config backend/.pre-commit-config.yaml
        env:
          PRE_COMMIT_HOME: backend/.cache/pre-commit

  test:
    name: Build & Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create docker network
        run: docker network create openhexa

      - name: Copy .env file
        run: cp .env.dist .env

      - name: Build docker app image
        env:
          DOCKER_BUILDKIT: 1
        run: docker compose build --build-arg DJANGO_SETTINGS_MODULE="config.settings.dev"

      - name: Run Django tests
        run: |
          docker compose run -e DEBUG=false -u $(id -u):$(id -g) app coveraged-test

      # Push on main
      - name: Build and push (on main)
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          context: backend
          target: app
          file: backend/Dockerfile
          build-args: |
            DJANGO_SETTINGS_MODULE=config.settings.dev
          cache-from: type=registry,ref=yolanfe/yf:buildcache
          cache-to: type=registry,ref=yolanfe/yf:buildcache,mode=max
          tags: |
            yolanfe/yf:main
            yolanfe/yf:latest
      